### ISSUE TITLE
Add the ability to set the primary band and to see used bands

### ISSUE THREAD

**Issue by SuperMitic** [4IceG/luci-app-modemband#17]
I have a ZTE MF289F and i would like to ask if it is possible to add the ability to set the primary (upload) band. This would be extremely helpful. In my case, i have B1+B3+B7+B20, but when i used all of them i get 250Mbps in Download but only a few Mbps in upload (it is choosing automatically the primary band). Instead if i set B3 as primary band alone i get 35Mbps in upload. 
Moreover, it would be great to have the ability to see the current used band. In fact right now, i can see only the set bands, but this doesn't mean that the modem is connected to all of them.

**Comment by obsy** [comment]
1. It is not possible to set "only" primary band. You can set only one band or two/three/four etc., but it is not possible to indicate which one is the primary one.
2. To see current bands use luci-app-3ginfo.
