### ISSUE TITLE
Support on Quectel RM500U-CNV

### ISSUE THREAD

**Issue by flammable47** [4IceG/luci-app-modemband#18]
Hello can it be possible to support the RM500U-CNV? here the data I got on my module, currently I'm using ZBT WG-1608 (16M) running OpenWrt 23.05.2.

exact name of modem and ew version number:
Quectel
RM500U-CNV
Revision: RM500UCNVAAR03A02M2G

VID and PID identifier on the USB bus:
Bus 002 Device 003: ID 2c7c:0900 Quectel RM500U-CNV

serial port used for communication with the modem ("diagnostic"):
/dev/ttyUSB2

AT command to read the set bands together with an example result:
AT+QNWPREFCFG=?
+QNWPREFCFG: "mode_pref",AUTO:WCDMA:LTE:NR5G:NR5G-SA:NR5G-NSA
+QNWPREFCFG: "gw_band",1:5:8
+QNWPREFCFG: "lte_band",1:3:5:8:34:38:39:40:41
+QNWPREFCFG: "nr5g_band",1:3:5:8:28:41:77:78:79
+QNWPREFCFG: "all_band_reset"
+QNWPREFCFG: "srv_domain",(0-2)
+QNWPREFCFG: "voice_domain",(0-3)
+QNWPREFCFG: "ue_usage_setting",(0,1)
+QNWPREFCFG: "roam_pref",(0-3)

an AT command to set specific bands
AT+QNWPREFCFG="mode_pref",AUTO

a list of all bands that can be set on the modem:
5GNR NSA   = n41, n78, n79
5GNR SA    = n1, n2, n3, n5, n8, n28, n41, n77, n78, n79
LTE-FDD    = B1, B3, B5, B8
LTE-TDD    = B34, B38, B39, B40, B41
UMTS/WCDMA = B1, B5, B8

**Comment by 4IceG** [comment]
Hi,
@flammable47 Check if it works, I also added modem to 3ginfo-lite package (you can also test it).

[modemband.zip](https://github.com/4IceG/luci-app-modemband/files/14075513/modemband.zip)
[3ginfo-lite.zip](https://github.com/4IceG/luci-app-modemband/files/14075520/3ginfo-lite.zip)

**Comment by flammable47** [comment]
> Hi, @flammable47 Check if it works, I also added modem to 3ginfo-lite package (you can also test it).
> 
> [modemband.zip](https://github.com/4IceG/luci-app-modemband/files/14075513/modemband.zip) [3ginfo-lite.zip](https://github.com/4IceG/luci-app-modemband/files/14075520/3ginfo-lite.zip)

Hello @4IceG 
I already check the package and it's works great..!!
![3ginfo](https://github.com/4IceG/luci-app-modemband/assets/34386522/0f204cde-4985-4924-8f02-8ac27c415676)
![Modem band 5G NSA](https://github.com/4IceG/luci-app-modemband/assets/34386522/1660b0d8-23d9-4310-87de-42da0341747e)
![Modem band 5G SA](https://github.com/4IceG/luci-app-modemband/assets/34386522/b9152cda-7f62-477f-b391-5dbacf66cf93)
![Modem band LTE](https://github.com/4IceG/luci-app-modemband/assets/34386522/13680f89-d3b9-4787-ad6e-720650836176)

**Comment by 4IceG** [comment]
Hi,
Unfortunately, it does not show all data and I do not know if it's the fault of the "ecm protocol" or if you modified the settings in modem. It should return the 5GNR NSA bands (they are completely missing from the settings), 3ginfo-lite does not show the data correctly either.

@flammable47 Can you restore the modem to default settings and run it on the qmi/mbim protocol?

**Comment by flammable47** [comment]
> Hi, Unfortunately, it does not show all data and I do not know if it's the fault of the "ecm protocol" or if you modified the settings in modem. It should return the 5GNR NSA bands (they are completely missing from the settings), 3ginfo-lite does not show the data correctly either.
> 
> @flammable47 Can you restore modem to default settings and run it on the qmi/mbim protocol?

It's only supported in ECM protocol or it can be NDIS, RNDIS, NCM?

**Comment by 4IceG** [comment]
OK, I understand, let's keep this "ecm".

@flammable47 Show command result:
`sms_tool -d /dev/ttyUSB2 at "at+qnwinfo;+qcainfo;+qeng=\"servingcell\";+qspn"`

maybe we will find out why 3ginfo-lite does not show data.

**Comment by flammable47** [comment]
> OK, I understand, let's keep this "ecm".
> 
> @flammable47 Show command result: `sms_tool -d /dev/ttyUSB2 at "at+qnwinfo;+qcainfo;+qeng=\"servingcell\";+qspn"`
> 
> maybe we will find out why 3ginfo-lite does not show data.

here the result of the script
![image](https://github.com/4IceG/luci-app-modemband/assets/34386522/d36effa7-8528-46cf-9751-ff86345905ca)

**Comment by 4IceG** [comment]
I don't know if it's OK now, unusual modem, strange AT commands.

[3ginfo-lite.zip](https://github.com/4IceG/luci-app-modemband/files/14085005/3ginfo-lite.zip)
