### ISSUE TITLE
Add Quectel RM502Q-GL

### ISSUE THREAD

**Issue by stich86** [4IceG/luci-app-modemband#20]
hi my friend @4IceG,

are you able to add to the custom band list also Quectel RM502Q-GL?
It's the global version ofr RM502Q family, here is the [datasheet](https://www.quectel.com/wp-content/uploads/2021/03/Quectel_RM502Q-GL_5G_Specification_V1.1.pdf) with the supported bands

i've used `2c7c0800RG502Q-EA` as template (renamig it `2c7c0800RM502Q-GL`) and it's working :)

**Comment by 4IceG** [comment]
Hi Hey Hello :) @stich86 , there will be no problem to add this modem.
