### ISSUE TITLE
I've rewrite this Chinese Simplified translation.

### ISSUE THREAD

**Issue by murraychou** [4IceG/luci-app-modemband#22]
[luci-app-modemband.zip](https://github.com/4IceG/luci-app-modemband/files/15281464/luci-app-modemband.zip)
Hello, developer:
I've change this Chinese Simplified translation file. I think it is more comprehensive than before.

**Comment by 4IceG** [comment]
Hi @murraychou ,
Ok, thanks for the better translation. I will use your translation in new compilation.
