### ISSUE TITLE
Working with modemmanager

### ISSUE THREAD

**Issue by Manu99it** [4IceG/luci-app-modemband#26]
In the last two days for an unrelated problem (frequent disconnections) I installed modemmanager. For curiosity I tried your packages and all worked without serious problems. Just sometimes they couldn't retrieve values from modem, but simply reloading the page/luci made them work. I was thinking that if the problem is the concurrent usage of qmi by modemmanager and your packages maybe you can use qmi-proxy of libqmi

**Comment by 4IceG** [comment]
Hi,
@Manu99it Sorry, but there is information in package description not to use my packages with MM. Multiple applications cannot use modem at the same time.

I will not fight with MM and specially modify packages. Create a package for LuCI that supports all MM functions, my packages will then be unnecessary.

**Comment by Manu99it** [comment]
> Multiple applications cannot use modem at the same time.

Yes but for example if one keep installed uqmi and modemmanager, these go effectively in conflict with modemmanager giving an error after some times that the modem can't be found. What I'm saying is that after uninstalling uqmi, your packages continue to work and modemmanager seems to not bother
