### ISSUE TITLE
No LTE B5 option

### ISSUE THREAD

**Issue by victor186** [4IceG/luci-app-modemband#30]
I installed openwrt for MF286A on my MF286C brazilian, but the luci-app-modemband don't have LTE B5 option.
How to set RAT ? (WCDMA only, LTE only, etc...)
![IMG_20240910_121717_121](https://github.com/user-attachments/assets/ae908a75-b2a6-4563-80a9-82853877bac7)

**Comment by victor186** [comment]
AT commands worked! Thanks
Where is the "modem settings template" tab ? Don't have in luci

**Comment by 4IceG** [comment]
@victor186 You are using an older version of LuCI package, install the latest version.

**Comment by victor186** [comment]
Thank you bro, now i have LTE band 5 option

**Comment by victor186** [comment]
> [@victor186](https://github.com/victor186) how did you install openwrt for MF286A on my MF286C brazilian as I don't know if i need download upgrade or install firmware. Any guide ?

Follow the guide for MF286A, the process is same, you need USB-Serial converter.

**Comment by victor186** [comment]
Don't forget the backup of stock firmware
