### ISSUE TITLE
luci-app-modemband apk package compile fails:

### ISSUE THREAD

**Issue by Jalakas** [4IceG/luci-app-modemband#32]
luci-app-modemband apk package compile fails:

> make[3] -C feeds/modemband/luci-app-modemband compile
> ERROR: info field 'version' has invalid value: package version is invalid
> ERROR: failed to create package: .../openwrt/bin/packages/mips_24kc/modemband/luci-app-modemband-1.0.25-20240519-r1.apk: package version is invalid
> make[3]: *** [.../openwrt/feeds/luci/luci.mk:381: .../openwrt/bin/packages/mips_24kc/modemband/luci-app-modemband-1.0.25-20240519-r1.apk] Error 99
> ERROR: package/feeds/modemband/luci-app-modemband failed to build.

I believe apk versions does not like dash in version, as here:
https://github.com/openwrt/packages/commit/bc14a5428b66e0a191417a47fb8a78884c8b607a

**Comment by 4IceG** [comment]
Hi @Jalakas ,
I fixed Makefile to be compatible with the apk.
